project:
  type: website

website:
  title: "ISSS608VAA-GROUP15-FINALPROJECT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Us"
      - href: ProjectOverview.qmd
        text: Project Overview
      - href: Storyboard.qmd
        text: Storyboard
      - href: User Guide.qmd
        text: UserGuide
      - href: Analysis and Results.qmd
        text: Analysis and Results
      - href: Shiny.qmd
        text: Shiny App Demo
      - href: Poster.qmd
        text: Poster
      - href: Prototype.qmd
        text: Prototype


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

